/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplicationbank;

import javax.swing.JOptionPane;
import model.AccountBank;

/**
 *
 * @author MacOS
 */
public class BankJFrame extends javax.swing.JFrame {

    /**
     * Creates new form BankJFrame
     */
    public BankJFrame() {
        initComponents();
        panelBankCus.setVisible(false);
        labelAmount.setVisible(false);
        txtAmountTranfer.setVisible(false);
    }

    AccountBank accountCus = null;
    AccountBank accountCusTranfer = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        panelLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        panelBankCus = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNameCus = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAmountCus = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAmountWithDraw = new javax.swing.JTextField();
        btnWithDraw = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtAccountTranfer = new javax.swing.JTextField();
        lbNameAccountTranfer = new javax.swing.JLabel();
        btnTranfer = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        txtAmountTranfer = new javax.swing.JTextField();
        labelAmount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Bank");

        jLabel1.setText("User");

        jLabel3.setText("Pass");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelLoginLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(txtPass))
                        .addGroup(panelLoginLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnLogin)))
                .addGap(74, 74, 74))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogin)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel4.setText("Name");

        txtNameCus.setEditable(false);

        jLabel5.setText("Amount");

        txtAmountCus.setEditable(false);

        jLabel6.setText("Amount Withdraw");

        btnWithDraw.setText("Withdraw");
        btnWithDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithDrawActionPerformed(evt);
            }
        });

        jLabel7.setText("Account Tranfer");

        txtAccountTranfer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAccountTranferKeyReleased(evt);
            }
        });

        btnTranfer.setText("Tranfer");
        btnTranfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranferActionPerformed(evt);
            }
        });

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        labelAmount.setText("Amount");

        javax.swing.GroupLayout panelBankCusLayout = new javax.swing.GroupLayout(panelBankCus);
        panelBankCus.setLayout(panelBankCusLayout);
        panelBankCusLayout.setHorizontalGroup(
            panelBankCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBankCusLayout.createSequentialGroup()
                .addGroup(panelBankCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBankCusLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(panelBankCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)))
                    .addGroup(panelBankCusLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnback))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBankCusLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelAmount)))
                .addGap(34, 34, 34)
                .addGroup(panelBankCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTranfer)
                    .addGroup(panelBankCusLayout.createSequentialGroup()
                        .addGroup(panelBankCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAmountTranfer, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnWithDraw, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNameCus, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAmountCus, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAmountWithDraw, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAccountTranfer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addComponent(lbNameAccountTranfer, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelBankCusLayout.setVerticalGroup(
            panelBankCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBankCusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBankCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNameCus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBankCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAmountCus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelBankCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAmountWithDraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnWithDraw)
                .addGap(31, 31, 31)
                .addGroup(panelBankCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAccountTranfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNameAccountTranfer, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelBankCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBankCusLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnback)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBankCusLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBankCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAmountTranfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAmount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(btnTranfer)
                        .addGap(40, 40, 40))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelBankCus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(panelBankCus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if (txtUser.getText().length() > 0 && txtPass.getText().length() > 0) {
            AccountBank checklogin = JavaApplicationBank.remote().checklogin(txtUser.getText(), txtPass.getText());
            if (checklogin.getCusNo() != null) {
                panelBankCus.setVisible(true);
                txtNameCus.setText(checklogin.getCusName());
                txtAmountCus.setText(checklogin.getBalance());
                panelLogin.setVisible(false);
                accountCus = checklogin;
            } else {
                JOptionPane.showMessageDialog(this, "Sai ten hoac mat khau", "Con dien", 0);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nhap day du ten va mat khau", "Con dien", 0);
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnWithDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithDrawActionPerformed
        if (txtAmountWithDraw.getText().length() > 0) {
            JavaApplicationBank.remote().withdraw(accountCus.getCusNo(), Float.valueOf(txtAmountWithDraw.getText()));

            Float amount = Float.valueOf(txtAmountCus.getText()) - Float.valueOf(txtAmountWithDraw.getText());
            txtAmountCus.setText(amount.toString());
            txtAmountWithDraw.setText("");

        } else {
            JOptionPane.showMessageDialog(this, "Nhap so tien can rut", "Con dien", 0);
        }


    }//GEN-LAST:event_btnWithDrawActionPerformed

    private void btnTranferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranferActionPerformed
        if (txtAmountTranfer.getText().length() > 0) {
            if (accountCusTranfer != null) {
                JavaApplicationBank.remote().transfer(accountCus.getCusNo(), Float.valueOf(txtAmountTranfer.getText()));
                JavaApplicationBank.remote().transferreciver(accountCusTranfer.getCusNo(), Float.valueOf(txtAmountTranfer.getText()));

                Float amount = Float.valueOf(txtAmountCus.getText()) - Float.valueOf(txtAmountTranfer.getText());
                txtAmountCus.setText(amount.toString());
                txtAmountTranfer.setText("");
                
                
            } else {
                JOptionPane.showMessageDialog(this, "Tai khoan khong ton tai", "Con dien", 0);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Nhap so tien can chuyen", "Con dien", 0);
        }

    }//GEN-LAST:event_btnTranferActionPerformed

    private void txtAccountTranferKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccountTranferKeyReleased
        AccountBank receivercode = JavaApplicationBank.remote().receivercode(txtAccountTranfer.getText());
        if (receivercode.getCusNo() != null) {
            lbNameAccountTranfer.setText(receivercode.getCusName());
            labelAmount.setVisible(true);
            txtAmountTranfer.setVisible(true);
            accountCusTranfer = receivercode;
        } else {
            lbNameAccountTranfer.setText("");
            labelAmount.setVisible(false);
            txtAmountTranfer.setVisible(false);
            accountCusTranfer = null;
            txtAmountTranfer.setText("");
        }

    }//GEN-LAST:event_txtAccountTranferKeyReleased

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        panelLogin.setVisible(true);
        panelBankCus.setVisible(false);
        txtUser.setText("");
        txtPass.setText("");
        txtAccountTranfer.setText("");
        txtAmountWithDraw.setText("");
    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnTranfer;
    private javax.swing.JButton btnWithDraw;
    private javax.swing.JButton btnback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelAmount;
    private javax.swing.JLabel lbNameAccountTranfer;
    private javax.swing.JPanel panelBankCus;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JTextField txtAccountTranfer;
    private javax.swing.JTextField txtAmountCus;
    private javax.swing.JTextField txtAmountTranfer;
    private javax.swing.JTextField txtAmountWithDraw;
    private javax.swing.JTextField txtNameCus;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
